image: docker.io/reclaimthestack/rails-example:latest
deployments:
  web:
    port: 3000
    replicas: 1
    memory: 512Mi
    cpu: 250m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
resources: {}
envFrom:
  - secretRef:
      name: rails-example
env: []
