apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAocTRa63lArOYMhbWJXlyFVynPo08U1Nh2A1kzQmF5GOA/EDpAWtUgZEYKYGx4DalTSHYcQeZgMyIpK+xMlKv/bVTHXxS46Het39O7I7DZ946PNpi8pR2tNrwNoYK+9qP5Bql8d46YMdY651nVlKJV+CwyjnAZWuzY65U70axnTerMNliR++PMnKyXxBPI5RW7tfTaGm8n+2AUka5mWWwiNEeEAPoQ8K0OJXTyFQaGyvqGgu0aZutmmc82t4L+vTgFXUD8+Wi4RpBicRDuUwq5I0h/QeZF6QrxBp02a7GgkSgrwI9euGbN1pciPMe5C9nTOhHGCEfPU/d300t7Claf0Cwf0GFYWNgNdgmGQiaSSfQ/XZ9QsffDaYoX6w07B6opYzr5kQ0V3TwaHwR4tg0JQ5pgBRjPtk7KtsVgQRIfdkm7kxu8tRaRQUiDsi7yrkquQMGngJay4byWSwpTECBWm68nGN/3ID2pLt3tOXQFzd/sWrQ1ojNTDPVGrt5UjeywTW44Iwnii3uZM2bqc6Tt8YR1LZD6VSSe4idChCwhnMnii8hL20GyUKi9Bvd/lnQvZYYL5C6we8o7PqgrKYkTLo2VsMW/oEBD6tSe+UETM6wRqiA3wjJKI35IHx4oS8AhZZ8Hg/JNtj5tn0NmWDGP2EZaraThCk6nbDbnYLuTC0OhXrziqeQ6OB02SZQJ760/rVUgwlMpscW8YoyfeMQ3kG5OT5k7l9puPse0GkQFJ6N6fVZLnz7S5wuJfqejqrdXWTUPHpszg3sp8GlqaaB0es/h0cI6AkXjUYipaTO3yy/UIywx9taoJbIr8GszXxIjbdMvOXSMPkgeCRUg0kO5VJodm775EiOgKt/Vl8AXiVmzmYYkyaEcTrdJIs/QBChuZJBBj7QGbRY9ds+1Nw70QQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

