apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAVu3KOxufwS5ufHMNoErl7gY+hAWMThIZb0k/2yFd5zeT3anH2H3jL/eGn40bTbR02hYGjCbPKEnYaIm4jHw3b9kaNophBRzZDpq4W1WjbCayMkeltLZtXw7bINGzXiEG2caumgnRGIXcYyDazz9D5YkCtcH3BcKn/Y+L8hwnOgiG86IjBql37EXPBDbWeoPXne7dAQGBpciq5ORYmZdUS1U9ovmx8zWZu/0JO+ikvWgB+EKY1SzZc7dUiiI5LNRsBkxyXH/gXjShG/9eysciJqNIQ87dyyKJucp5H6xXYZ6ARpiDd5LkjM6uoTKkzJIsLlu0aZtTnzsUG5b8q6N0wA5lHp7gXYecVJnAGvQ+WCu9VRnyq98/6MFCvmibP4Xk57dJ4XBsjPwGzs5CP5RShL+xE6wSlfueSMjyamD4i+liFQaZUbCHHZrV2fMtF+yz+VMzMFZzAHYPDQam8KmhrQFcy3/CiHVpkgIFqYAq/qClIXJqWPBA5vhMOaILzWPYVV/Aa3+gW7hCPcVHdLHOzGynxmhfdSRvH/3uIKZKoUbFCD6h8fcSUFzPk6xknJ5KbMHf7qZM7wd25eZN4Z6XihnAV4EWxs+7BqMQXvL2orC7Xwgt9DJt3PHeiFihKCp3dKAW8yPx/TgQvS2UisL+u+FvwDLj/thFOKPuuqt2X+i1ONkTSq2yjoUwymipXuNis8EGK9DRcufoigh5RdaOWwoEKL13xgQBA5ruadS3tusxXsW/p+zqXFpZw+o8kg2ovhkh6IrDuzrGMFcY4JBby/afyynRQnjBUFY+TG/buaLn16tnTNHLIMoxB781MqnM2k5rzJmBHCJlv4hDgPU3CWCqIa1VzhFzZFPE/em4eNr/824KLvIidr9EQcLctc76wxn6a5BxiBxH7oFKNrvxelQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

