# Creates a Deployment and Service for a web application listening on .Values.web.port.
#
# Liveness and readiness probes are commented out by default. You may want to make
# an initial deploy without them and figure out which requests to use before enabling.
#
# Example values.yaml:
# image: docker.io/reclaimthestack/rails-example:latest
# deployments:
#   web:
#     port: 3000
#     replicas: 1
#     memory: 512Mi
#     cpu: 250m
#     # Put ENV which should only apply to the web deployment here
#     env:
#       - name: WEB_CONCURRENCY
#         value: "2"
#     # command: <custom-command> (if you don't want to run bin/rails server)
# envFrom:
#   - secretRef:
#       name: rails-example # Create a dedicated application secret with k secrets:create rails-example
# env: [] # Put ENV which applies to all deployments here

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.deployments.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: web
    spec:
      containers:
        - name: web
          image: {{ .Values.image }}
          command:
            - sh
            - -c
            - {{ .Values.deployments.web.command | default "bin/rails server" }}
          ports:
            - containerPort: {{ .Values.deployments.web.port }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
          {{- if .Values.deployments.web.readinessProbePath }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployments.web.readinessProbePath }}
              port: {{ .Values.deployments.web.port }}
          {{- end }}
          resources:
            limits:
              memory: {{ .Values.deployments.web.memory }}
              cpu: {{ .Values.deployments.web.cpu }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.web.env }}
            {{- .Values.deployments.web.env | toYaml | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "{{ .Values.deployments.web.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployments.web.port }}
      targetPort: {{ .Values.deployments.web.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-web
