apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-example
  namespace: default
spec:
  encryptedData:
    RAILS_ENV: AgCN1VvCv0Ls60U3iei9KdoGqDkU6Qs2v8OAEkV5UX2OWeHgRLUxmLK4lFHKQXUJc+IgbF74IGjuI6zxhqeSci9C9C+/19dLobMYSbjXatQghKH83RIwy6KAglLKPHuECY9+8O9i7vBx8EdxUlfPBqJyZCrABAhileHGVS4K4xw+Qtm6LGWxL/cOFpr5ZP55wc4impz6QqfZTTLv1er/5n/qxgX429GFS3LH4VwyF/dtpJmw4TbRkkpODd+SEp/c820RtY6kSwgq+LyA1dYYMxhMiIDemZizDhAEjih2CTU/fRA+eOTveYCj2a+ZZJb1oVuUk+/Ja55u7UfRLzOJMc4tT7cz5FottqI9J/UiQKyj5I591gA7nGXE6zppkl1Mxv9Ik6VGO1hhY4YVEB3sD+rsdwH0W/5mzDveur7kbY/2vgI4Q1GVaUx4/JlvpDwbZUtF4Kb6QL5AT8Nf5Hx50sR5JDp5m0PINb9cOFpBYP1DVaS9dbdYHUJVEoV34PtvISUoQZSI7lpHkzPvEGkUk1A9NdeHKOQTl4OnA8ZvR93AOYsmzhNqwAprxWKIiHLoU1y/MQrVdKGzJwaCLsIXlAn8VIUol5/ROBeCDjCVWdpJ3c9jXZG13lRm7NvmogBw39SNEnnsz8nlQj5gTogPbgvbxncSokFrmkrkqg6eoJga5bJdTgrOOLZNDgiMG7dGKWkoOVFTZeSNmysR
    SECRET_KEY_BASE: AgBX0IZoxwxnV1UHDZ/M3HlkUyNhz0HeITp2nOS0Y6jbvvcH1vJ8zaNCFc/ZXLFknsNGOEOFfyQ+QcMEjOMBB1vGFcj33HH5toOLYBUM9M+8CdwKPg4fsR3aY6oslc2rmg2rCgD4VKbbncgIiU8hHQTCFZS5AfNyOApy0v1NJvxZz69N0g8z1fUpFvBSE+vP9GTU36tIoudGKr9aHNBuZpKWFoSoZfv0nXaGlKAIDkoQNz7l/dgCjbK451gKEwJSYtL0GfJQCDkOy0/NLh9Bkyk36FEcFfV2ATUZnF8qEfk/mvM1Vyyw1M2OTDf6zFTNAZmnsXMw3I9I9ZY53wcZ/LjOUWbw15XG8oTw1i5yKkOr4TsoH+qtmUHB6rsFhpIQAvhutj28/uNsm6NL5w2835ROt0yrtfSYBjdi8WF1aX9TNdZe69aNK1XG+84lRVX0WK/iMY6ofy6lGk5me3W0+RKWZ69kyyfX5ohMEdPn18GzbjDYJwqSgBwGba7rsv07lG/yJ28ho+eb/VmxWro2JdnWlYJXtF+C6rEtTUMhVhipawJLEBaosE7TooHNrtYjeVZZTW4UqzYsVwetO6Dev0yQfp3tIQnIcfHwRp8AOmPq6qi7txM+0ckqqK+4lgksT0sUCEiy3SCxG0OcR/wCmAgxQESu//oUUMXa49uD9YPJsjwaZcwJJNRpgJ9cQm85/xMGKm4=
  template:
    metadata:
      creationTimestamp: null
      name: rails-example
      namespace: default
    type: opaque

